spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://192.168.64.2:30306/order-db
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sa-mini-project2-realm-prod
          jwk-set-uri: http://localhost:8080/realms/sa-mini-project2-realm-prod/protocol/openid-connect/certs

server:
  port: 8085

product-service-secret-key: "3e02714e-4d78-11ed-bdc3-0242ac120002"
payment-service-secret-key: "3e026eba-4d78-11ed-bdc3-0242ac120002"
account-service-secret-key: "3e026744-4d78-11ed-bdc3-0242ac120002"
account-service-url: http://localhost:8081/service/account
product-service-url: http://localhost:8087/service/products/
payment-service-url: http://localhost:8086/api/payment/
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql:3306/order-db
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL}
          jwk-set-uri: ${KEYCLOAK_JWK_URL}

server:
  port: 8080

product-service-secret-key: ${PRODUCT_SERVICE_SECRET_KEY}
payment-service-secret-key: ${PAYMENT_SERVICE_SECRET_KEY}
account-service-secret-key: ${ACCOUNT_SERVICE_SECRET_KEY}
product-service-url: ${PRODUCT_SERVICE_URL}
payment-service-url: ${PAYMENT_SERVICE_URL}
account-service-url: ${ACCOUNT_SERVICE_URL}

