spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://192.168.64.2:30306/product-db
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8087

product-quantity-threshold: 10
product-service-secret-key: "3e02714e-4d78-11ed-bdc3-0242ac120002"
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql:3306/product-db
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

product-quantity-threshold: ${PRODUCT_QUANTITY_THRESHOLD}
product-service-secret-key: ${PRODUCT_SERVICE_SECRET_KEY}