apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30085
  selector:
    app: order-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: phatnguyentan/order-service:1.0.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: PRODUCT_SERVICE_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: product-service-secret-key
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

