spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://192.168.64.2:30306/account-db
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081
account-service-secret-key: "3e026744-4d78-11ed-bdc3-0242ac120002"
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql:3306/account-db
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080
account-service-secret-key: ${ACCOUNT_SERVICE_SECRET_KEY}
