apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30087
  selector:
    app: account-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: phatnguyentan/account-service:1.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: ACCOUNT_SERVICE_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: service-configmap
                  key: account-service-secret-key
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

