apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30085
  selector:
    app: order-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: phatnguyentan/order-service:1.0.5
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: KEYCLOAK_ISSUER_URL
              valueFrom:
                configMapKeyRef:
                  name: service-configmap
                  key: keycloak-issuer-url
            - name: KEYCLOAK_JWK_URL
              valueFrom:
                configMapKeyRef:
                  name: service-configmap
                  key: keycloak-jwk-url
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-configmap
                  key: product-service-url
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-configmap
                  key: payment-service-url
            - name: ACCOUNT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-configmap
                  key: account-service-url

            - name: PRODUCT_SERVICE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: product-service-secret-key
            - name: PAYMENT_SERVICE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: payment-service-secret-key
            - name: ACCOUNT_SERVICE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: account-service-secret-key
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

