apiVersion: v1
kind: Service
metadata:
  name: paypal-service
  labels:
    app: paypal-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30089
  selector:
    app: paypal-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypal-service
  labels:
    app: paypal-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paypal-service
  template:
    metadata:
      labels:
        app: paypal-service
    spec:
      containers:
        - name: paypal-service
          image: phatnguyentan/paypal-service:1.0.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: SHIPPING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-configmap
                  key: shipping-service-url
            - name: ACCOUNT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-configmap
                  key: account-service-url

            - name: SHIPPING_SERVICE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: shipping-service-secret-key
            - name: ACCOUNT_SERVICE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: account-service-secret-key
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

