apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30087
  selector:
    app: product-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: phatnguyentan/product-service:1.0.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: PRODUCT_SERVICE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: product-service-secret-key
            - name: PRODUCT_QUANTITY_THRESHOLD
              valueFrom:
                configMapKeyRef:
                  name: service-configmap
                  key: product-quantity-threshold
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

