apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30088
  selector:
    app: shipping-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: phatnguyentan/shipping-service:1.0.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

